repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-merge-conflict
          - id: debug-statements
          - id: destroyed-symlinks
          - id: end-of-file-fixer
          - id: mixed-line-ending
          - id: trailing-whitespace
    - repo: https://github.com/ambv/black
      rev: 21.8b0
      hooks:
          - id: black
            language_version: python3.9
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
